### ISSUE TITLE
Caterpillar is way too hard to play

### ISSUE THREAD

**Issue by petrisch** [mariusrubo/mariusrubo.github.io#1]
Can't you make like differnt levels of difficulties ;-)

**Comment by mariusrubo** [comment]
Haha no this game should be at least as difficult as Dark Souls ;-) 
Here's what it looks like after some time: https://www.youtube.com/watch?v=yC1Rs7nieBE

**Comment by petrisch** [comment]
Your such a maniac, nice. I have to practice harder i guess.
